[package]
name = "codec"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Audio CODEC server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.64"
log-server = { package = "xous-api-log", version = "0.1.60" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.60" }
xous-names = { package = "xous-api-names", version = "0.9.62" }
log = "0.4.14"
susres = { package = "xous-api-susres", version = "0.9.60" }
llio = { path = "../llio" }
trng = { path = "../trng" }

xous-ipc = "0.10.1"
num-derive = { version = "0.3.3", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
rkyv = { version = "0.8.8", default-features = false, features = [
    "std",
    "alloc",
] }

utralib = { version = "0.1.25", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
default = []
