[package]
name = "rkyv-test2"
version = "0.1.0"
edition = "2021"

[dependencies]
rkyv = { version = "0.8.8", default-features = false, features = [
    "std",
    "alloc",
    "bytecheck",
] }
xous = { version = "0.9.70", features = ["forget-memory-messages"] }
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
