[package]
name = "bao1x-mbox2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utralib = { version = "0.1.26", optional = true, default-features = false }
xous-api-names = "0.9.69"
xous-api-ticktimer = "0.9.67"
xous = "0.9.68"
log-server = { package = "xous-api-log", version = "0.1.67" }
log = "0.4.14"
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.14", default-features = false }

[features]
"bao1x" = ["utralib/bao1x"]
# ext specifies to use the APB client, instead of the loopback local
"ext" = []          # must match setting in bao1x-mbox1
default = ["bao1x"]
