[package]
name = "wycheproof-import"
version = "0.1.0"
edition = "2018"

[dependencies]
eyre = "0.6.5"
serde = { version = "1.0.129", features = ["derive"] }
serde_json = "1.0.66"
serde_with = { version = "1.9.4", features = ["hex"] }
