[package]
name = "jtag"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "JTAG port server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.36"
log-server = { package = "xous-api-log", version = "0.1.31" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.31" }
xous-names = { package = "xous-api-names", version = "0.9.33" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {package = "xous-api-susres", version = "0.9.31"}

xous-ipc = "0.9.36"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

utralib = { version = "0.1.15", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
hazardous-debug = []
dvt = []
dry-run = [] # just prints keys but doesn't burn them
default = []
