[package]
name = "backup-vault2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbor = { path = "../cbor", package = "cbor-vault2" }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
