[package]
name = "swaptest1"
version = "0.1.0"
edition = "2024"

[dependencies]
xous = { version = "0.9.70", features = ["raw-trng"] }
xous-ipc = "0.10.10"
xous-names = { package = "xous-api-names", version = "0.9.71" }
ticktimer = { package = "xous-api-ticktimer", version = "0.9.70" }
log-server = { package = "xous-api-log", version = "0.1.69" }
log = "0.4.14"
arbitrary-int = "1.2"
