[package]
name = "ed25519-dalek-bao1x"
version = "2.2.0"
edition = "2021"
authors = [
    "isis lovecruft <isis@patternsinthevoid.net>",
    "Tony Arcieri <bascule@gmail.com>",
    "Michael Rosenberg <michael@mrosenberg.pub>",
]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/dalek-cryptography/curve25519-dalek/tree/main/ed25519-dalek"
homepage = "https://github.com/dalek-cryptography/curve25519-dalek"
documentation = "https://docs.rs/ed25519-dalek"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Fast and efficient ed25519 EdDSA key generations, signing, and verification in pure Rust."
exclude = [".gitignore", "TESTVECTORS", "VALIDATIONVECTORS", "res/*"]
rust-version = "1.81"

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "docs/assets/rustdoc-include-katex-header.html",
    "--cfg",
    "docsrs",
]
features = ["batch", "digest", "hazmat", "pem", "serde"]

[dependencies]
# custom package ref because Cargo isn't respecting the fiat-crypto backend request
curve25519-dalek = { package = "curve25519-dalek-bao1x", path = "../curve25519-dalek-bao1x", default-features = false, features = [
    "digest",
] }
ed25519 = { version = ">=2.2, <2.3", default-features = false }
signature = { version = ">=2.0, <2.3", optional = true, default-features = false }
# Use the hardware accelerated SHA hasher
sha2 = { package = "sha2-bao1x", path = "../sha2-bao1x", default-features = false }
subtle = { version = "2.3.0", default-features = false }

# optional features
merlin = { version = "3", default-features = false, optional = true }
rand_core = { version = "0.6.4", default-features = false, optional = true }
serde = { version = "1.0", default-features = false, optional = true }
zeroize = { version = "1.5", default-features = false, optional = true }

# HW interface for print debugging
utralib = { version = "0.1.27", optional = true, default-features = false }

[dev-dependencies]
curve25519-dalek = { package = "curve25519-dalek-bao1x", path = "../curve25519-dalek-bao1x", default-features = false, features = [
    "digest",
    "rand_core",
] }
x25519-dalek = { version = "2", default-features = false, features = [
    "static_secrets",
] }
blake2 = "0.10"
sha3 = "0.10"
hex = "0.4"
bincode = "1.0"
serde_json = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }
hex-literal = "0.4"
rand = "0.8"
rand_core = { version = "0.6.4", default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.7" }

[[bench]]
name = "ed25519_benchmarks"
harness = false
required-features = ["rand_core"]

[features]
# add print debugging
debug = ["utralib"]
default = ["fast", "std", "zeroize"]
alloc = [
    "curve25519-dalek/alloc",
    "ed25519/alloc",
    "serde?/alloc",
    "zeroize/alloc",
]
std = ["alloc", "ed25519/std", "serde?/std", "sha2/std"]

batch = ["alloc", "merlin", "rand_core"]
fast = ["curve25519-dalek/precomputed-tables"]
digest = ["signature/digest"]
# Exposes the hazmat module
hazmat = []
# Turns off stricter checking for scalar malleability in signatures
legacy_compatibility = ["curve25519-dalek/legacy_compatibility"]
pkcs8 = ["ed25519/pkcs8"]
pem = ["alloc", "ed25519/pem", "pkcs8"]
rand_core = ["dep:rand_core"]
serde = ["dep:serde", "ed25519/serde"]
zeroize = ["dep:zeroize", "curve25519-dalek/zeroize"]
