[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Program to test the log server"
edition = "2018"
name = "log-test-client"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.66"

[features]
default = []
