[package]
name = "tts-frontend"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Text to speech integration server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.38"
xous-ipc = "0.9.38"
log-server = { package = "xous-api-log", version = "0.1.33" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.33" }
xous-names = { package = "xous-api-names", version = "0.9.35" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
# xous-tts-backend = {path="../../../tts-backend"}
xous-tts-backend = "0.1.4"
codec = {path = "../codec"}

utralib = { version = "0.1.16", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
tts = []
default = []
