[package]
name = "usbd_scsi"
version = "0.1.1"
authors = ["cs2dsb <cs2dsb@gmail.com>"]
edition = "2018"
description = "usb-device implementation that provides a USB scsi transparent command set subclass"
categories = ["embedded"]
keywords = ["usb", "embedded", "no_std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/cs2dsb/stm32-usb.rs"
readme = "README.md"
documentation = "https://docs.rs/usbd_scsi"
homepage = "https://github.com/cs2dsb/stm32-usb.rs/tree/master/firmware/usbd_scsi"


[dependencies]
usb-device               = "0.2.4"
embedded-hal             = "0.2.3"
nb                       = "0.1.2"
typenum                  = "1.11.2"
itm_logger               = { version = "0.1.0", default-features = false }
uf2_block                = { version = "0.1.0", path = "../uf2_block" }
usbd_mass_storage     = { version = "0.1.0", path = "../usbd_mass_storage" }
packing               = { version = "0.2.0", path = "../packing/packing" }
usbd_bulk_only_transport = { version = "0.1.0", path = "../usbd_bulk_only_transport" }

[features]
trace-bot-headers   = [ "usbd_bulk_only_transport/trace-bot-headers" ]
trace-bot-states    = [ "usbd_bulk_only_transport/trace-bot-states" ]
trace-bot-bytes     = [ "usbd_bulk_only_transport/trace-bot-bytes" ]
trace-bot-zlp       = [ "usbd_bulk_only_transport/trace-bot-zlp" ]
trace-bot-buffer    = [ "usbd_bulk_only_transport/trace-bot-buffer" ]
trace-usb-control   = [ "usbd_bulk_only_transport/trace-usb-control" ]
trace-scsi-command  = []
trace-scsi-fs       = []
trace-all           = [ "trace-bot-headers", "trace-bot-states", "trace-bot-bytes", 
                        "trace-bot-zlp", "trace-bot-buffer", "trace-scsi-command", 
                        "trace-scsi-fs", "trace-usb-control" ]