[package]
name = "engine-25519"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Curve25519 Engine"

# Dependency policy: nail down all dependencies to the minor version number, so that changes to the code base are deliberate acts.
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { path = "../log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"
susres = {path = "../susres"}
llio =  {path = "../llio"} # temporary for testing some power stuff

xous-ipc = {path="../../xous-ipc"}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[dependencies.engine25519-as]
git="https://github.com/betrusted-io/engine25519-as.git"
rev="274b82899d28535ac6d4b7869e26eef2039578d5"
default-features = false
features = []

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
default = []
