[package]
name = "engine-25519"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Curve25519 Engine"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.46"
log-server = { package = "xous-api-log", version = "0.1.42" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.42" }
xous-names = { package = "xous-api-names", version = "0.9.44" }
log = "0.4.14"
susres = {package = "xous-api-susres", version = "0.9.42"}
llio =  {path = "../llio"} # temporary for testing some power stuff
utralib = { version = "0.1.20", optional = true, default-features = false }

xous-ipc = "0.9.46"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[dependencies.engine25519-as]
git="https://github.com/betrusted-io/engine25519-as.git"
rev="d249c967556b02ab5439eacb5078fa00c60b93d6"
default-features = false
features = []

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
default = []
