[package]
name = "swaptest2"
version = "0.1.0"
edition = "2024"

[dependencies]
xous = { version = "0.9.68", features = ["raw-trng"] }
xous-ipc = "0.10.8"
xous-names = { package = "xous-api-names", version = "0.9.69" }
ticktimer = { package = "xous-api-ticktimer", version = "0.9.67" }
log-server = { package = "xous-api-log", version = "0.1.67" }
log = "0.4.14"
arbitrary-int = "1.2"
