[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Program to test AES hardware support"
edition = "2018"
name = "aes-test"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
aes = { path = "../aes" }
hex-literal = "0.3.1"
log = "0.4.14"
log-server = { package = "xous-api-log", version = "0.1.56" }
xous = "0.9.60"

[features]
default = []
low_level_tests = []
